exclude:
  - node_modules
  - script

kramdown:
  input: GFM # Github Flavored Markdown
  math_engine: katex # 防止行间公式渲染错误

sass:
  style: :compressed

theme: jekyll-theme-primer

github:
  private: false
  license:
    name: MIT
  source:
    branch: "master"
    path: "/"
  repository_url: "https://github.com/YohnWang/YohnWang.github.io"
  
title: Pikachu's Blog
description: under construction
